### ISSUE TITLE
Path next to File Upload fields is not representative

### ISSUE THREAD

**Issue by axelvnk** [thomasmore-imd/one.weareimd.be#1]
![fakepath](https://cloud.githubusercontent.com/assets/6803540/5626157/cd9929d0-9587-11e4-9e9d-7123564226aa.png)
Structure of file path seems like a temp fix.
"C:/fakepath/image.filetype"

This problem occurs on registration pages as well as any page where a file input field is used.

**Comment by thomasdbock** [comment]
The fakepath is a javascript solution, because javascript cannot access the user's filesystem, they change the full name to fakepath. The reason you see this is because we changed the input field and used javascript to display the name of the file picked. We can either change the layout of the inputfield another way, or just return the filename and not the absolute path. Will look into it asap.

**Comment by axelvnk** [comment]
Showing only the filename seems good enough.
